"use client";
import localFont from "next/font/local";
import "./globals.css";
import Aside from "@/components/Aside";
import React, { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Robert's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false);

  const openDrawer = () => setIsOpen(true);
  const closeDrawer = () => setIsOpen(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Aside
          isOpen={isOpen}
          closeDrawer={closeDrawer}
          openDrawer={openDrawer}
        />
        {children}
      </body>
    </html>
  );
}
